config/routes.rb
AppMt::Application.routes.draw do
  root :to => 'home#index'
  match 'logout' => 'sessions#destroy'

  
  resources :chats, :only => [:index,:create] do
    collection do
      post 'change_room'
    end  
  end
  
  resources :sessions, :only => :create

end

app/models/channel.rb
class Channel < ActiveRecord::Base
  has_many :chats 
  
  attr_accessible :name
end

app/models/chat.rb
class Chat < ActiveRecord::Base
  belongs_to :channel
  
  attr_accessible :channel_id, :username, :message
  
  MAX_LOGGING = 10
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  
  def no_session
    redirect_to root_url unless session[:username] && session[:channel]
  end
end

app/controllers/chats_controller.rb
require 'pusher'

Pusher.app_id = '19198'
Pusher.key = '768124b90277f5c9ca27'
Pusher.secret = '91b827b86d2101f56ee3'

class ChatsController < ApplicationController
  before_filter :no_session, :get_channel
  
  def index
    @chats = @channel.chats.last(Chat::MAX_LOGGING)
    @channels = Channel.all
  end
  
  def create
    message = params[:message]
    Pusher[@channel.name].trigger('chatting', {:message => message, :username => @username})
    #Logging
    Chat.create(:channel_id => @channel.id, :username => @username, :message => message)
    head(:ok)
  end
  
  def change_room
    session[:channel] = params[:channel]
    
    redirect_to chats_url
  end
  
private
  def get_channel
    @channel  = Channel.find(session[:channel])
    @username = session[:username]
  end  
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @channels = Channel.all 
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  
  def create
    session[:username] = params[:username]
    session[:channel]  = params[:channel]

    redirect_to chats_url
  end
  
  def destroy
    session[:username] = session[:channel] = nil

    redirect_to root_url
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/chats/index.html.erb
<script src="http://js.pusher.com/1.11/pusher.min.js"></script>
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js"></script>

<h4>You are in room <%= @channel.name %></h4>

<table class="chat-table">
  <% @chats.each do |chat| %>	
  	<tr>
      <td><%= @username == chat.username ? "You" : chat.username %></td>
  	  <td>:</td>
  	  <td><%= chat.message %></td>
    </tr>		
  <% end %>
</table>	

<br/>
<%= form_tag('/chats', :method => :post) do -%>
  <div><%= text_field_tag 'message'%><%= submit_tag 'Ok', :class => "submit-text"%></div>
<% end -%>

<br/>
<div style="float:left;"><%= link_to 'Logout', logout_url %>&nbsp;</div>
<div style="float:left;"><%= link_to 'Change Room', '#', :class => 'change-room'%>
  <br/>
  <%= form_tag('/chats/change_room', :method => :post, :class => "change-room-form", :style => "display:none;padding-top:4px;") do -%>
    <div>
  	  <%= select_tag "channel", options_from_collection_for_select(@channels, "id", "name") %> 
  	  <%= submit_tag 'Ok' %>
    </div>
  <% end -%>
</div>

<script>
  var pusher = new Pusher('768124b90277f5c9ca27'); // Replace with your app key
  var channel = pusher.subscribe('<%= @channel.name %>');

  channel.bind('chatting', function(data) {
  	var username = '<%= @username %>' == data.username ? "You" : data.username;
  	var html='<tr><td>'+username+'</td><td>:</td><td>'+data.message+'</td></tr>';
  	$('.chat-table').append(html);
  });
  
  $('.submit-text').click(function() {
  	var dt = $(this).parents('form').serialize();
  	$.ajax({
      url: "/chats",
      type: "POST",
      data: dt,
      success: function() {
      	$('#message').val('');
      }
    });
  	return false;
  });


  $('.change-room').click(function() {
  	$('.change-room-form').toggle('slow');
  	return false;
  });
</script>

app/views/home/index.html.erb
<h4>Welcome to MidChat</h4>
<%= form_tag('/sessions', :method => :post) do -%>
  <table>
  	<tr>
      <td>Username</td><td>:</td><td><%= text_field_tag 'username'%></td>
    </tr>
    <tr>
      <td>Room</td><td>:</td><td><%= select_tag "channel", options_from_collection_for_select(@channels, "id", "name") %></td>
    </tr>
    <tr>
    	<td colspan="3"><%= submit_tag 'Enter', :class => "submit-text" %></td>
    </tr>
  </table>
<% end -%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AppMt</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>